# Generated by Django 6.0.3 on 2026-05-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('km_atual', models.IntegerField()),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('km_inicial', models.IntegerField()),
                ('km_final', models.IntegerField()),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_frotas_app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('consumo_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_frotas_app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_frotas_app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_frotas_app.veiculo')),
            ],
        ),
    ]
