# Generated by Django 6.0.3 on 2026-06-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_frotas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_frotas_app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='LocalizacaoDoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gest_frotas_app.veiculo')),
            ],
        ),
    ]
